apiVersion: v1
kind: Service
metadata:
  name: skiapp-service
  namespace: team-riker
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  type: NodePort
  selector:
    app: skiapp
